-- KidSkill Connect — table privileges.
--
-- Enabling RLS and writing policies is only half of access control. A policy narrows
-- what a role may reach; it cannot grant reach in the first place. Recent Supabase
-- images ship a secure-by-default ACL, so tables created in `public` land with only
-- TRUNCATE/REFERENCES/TRIGGER for `authenticated` — every policy in 0001 was being
-- evaluated against a role that could not SELECT at all.
--
-- These grants are written out one table at a time rather than as a blanket
-- `GRANT ALL ON ALL TABLES`, because the interesting part of this schema is what is
-- *not* granted. Read the DML column of each line as the real access-control summary;
-- the policies then narrow it to the right rows.
--
-- Nothing is granted to `anon`. Every screen in this product requires a signed-in
-- user, and search runs server-side under the parent's own session.

-- ---------------------------------------------------------------- service role

-- The service role is server-only and bypasses RLS. Exactly one thing in this product
-- uses it: the NotificationProvider, which has to mark a `notifications` row as sent
-- or failed on behalf of a recipient it is not authenticated as. It gets the same
-- secure-by-default treatment as everyone else, so it is granted here rather than
-- assumed — and it is granted broadly on purpose, because a role that bypasses RLS
-- gains nothing from a narrow column list.
grant usage on schema public to service_role;
grant all on all tables    in schema public to service_role;
grant all on all sequences in schema public to service_role;
grant all on all functions in schema public to service_role;

-- ---------------------------------------------------------------- reference data

-- Categories are a fixed list, readable by anyone signed in.
grant select on public.categories to authenticated;

-- ---------------------------------------------------------------- identity

-- Profiles are readable across roles so a parent can see a trainer's name and a
-- trainer can see who enquired. `profiles_self` restricts writes to your own row.
grant select, insert, update on public.profiles to authenticated;

-- A parent manages their own children; `children_owner` scopes every row.
grant select, insert, update, delete on public.children to authenticated;

-- Trainer profiles are public to signed-in users — this is the shop window.
grant select, insert, update on public.trainer_profiles to authenticated;

-- Trainers may apply (insert) but never approve: `trainer_categories_admin` is the
-- only UPDATE policy and it requires is_admin(). Rate edits go through
-- set_category_rate(), which is security definer, so no UPDATE grant is needed here.
grant select, insert on public.trainer_categories to authenticated;
grant update on public.trainer_categories to authenticated;

-- ---------------------------------------------------------------- matching

-- Enquiries are the one thing a parent creates directly. No DELETE: withdrawing is a
-- status change, so an enquiry that was sent stays on the record.
grant select, insert, update on public.enquiries to authenticated;

-- SELECT only, deliberately. Enrollments are created by accept_enquiry() and moved to
-- active by fund_enrollment(), both security definer. There is no path by which a
-- client writes an enrollment, and therefore none by which it invents a rate.
grant select on public.enrollments to authenticated;

-- UPDATE is what lets a trainer mark attendance; `sessions_trainer_update` limits it
-- to their own enrollments, and trg_release_session_funds rejects the update unless it
-- carries an assessment note and a rating. No INSERT: the month's classes are
-- generated by fund_enrollment().
grant select, update on public.sessions to authenticated;

-- ---------------------------------------------------------------- money

-- SELECT only. Accounts are opened by trg_bootstrap_accounts when a profile appears.
grant select on public.accounts to authenticated;

-- SELECT only, and this is the invariant made structural rather than merely intended:
-- there is no INSERT, no UPDATE and no DELETE for any client role on the ledger. Every
-- row in it is written by a trigger or a security-definer function. Balances are read
-- from the view below, never stored.
grant select on public.ledger_entries to authenticated;

grant select on public.account_balances   to authenticated;
grant select on public.enrollment_progress to authenticated;

-- ---------------------------------------------------------------- feedback + notifications

grant select, insert, update on public.feedback to authenticated;

-- UPDATE exists only so a recipient can stamp read_at. Notifications themselves are
-- written by enqueue_notification() and by the two notify triggers.
grant select, update on public.notifications to authenticated;

-- ---------------------------------------------------------------- functions

-- Postgres grants EXECUTE to PUBLIC by default, so these are belt-and-braces: they
-- state the intended callable surface explicitly, and they survive a database whose
-- default ACL revokes it.
grant execute on function public.search_trainers(double precision, double precision, uuid, integer, numeric) to authenticated;
grant execute on function public.my_location()                     to authenticated;
grant execute on function public.trainer_location(uuid)            to authenticated;
grant execute on function public.child_progress_spine(uuid)        to authenticated;
grant execute on function public.send_enquiry(uuid, uuid, uuid, text) to authenticated;
grant execute on function public.withdraw_enquiry(uuid)            to authenticated;
grant execute on function public.accept_enquiry(uuid, integer)     to authenticated;
grant execute on function public.decline_enquiry(uuid, text)       to authenticated;
grant execute on function public.fund_enrollment(uuid)             to authenticated;
grant execute on function public.set_category_rate(uuid, numeric)  to authenticated;
grant execute on function public.is_admin()                        to authenticated;

-- Admin-only entry points. They check is_admin() internally as well — the grant is a
-- second lock on the same door, not the only one.
grant execute on function public.admin_active_services(enrollment_status)  to authenticated;
grant execute on function public.review_trainer_category(uuid, boolean, text) to authenticated;
grant execute on function public.admin_refund_enrollment(uuid, text)       to authenticated;

-- enqueue_notification stays revoked from client roles: it is called only from inside
-- other security-definer functions and from the notify triggers. Letting a client call
-- it would let anyone send anyone a message.
revoke execute on function public.enqueue_notification(uuid, text, jsonb) from anon, authenticated;
